// ==UserScript==
// @name        DETECT_CMP
// @namespace   http://tampermonkey.net/
// @version     2026-03-12
// @description Detect what is the CMP used in this website and what kind of cookies you will find on it.
// @author      GrantHalf
// @match       *://*/*
// @icon        data:image/svg+xml;base64,PHN2ZyB3aWR0aD0iMTIwIiBoZWlnaHQ9IjEyMCIgdmlld0JveD0iMCAwIDEyMCAxMjAiIHhtbG5zPSJodHRwOi8vd3d3LnczLm9yZy8yMDAwL3N2ZyI+PGNpcmNsZSBjeD0iNjAiIGN5PSI2MCIgcj0iNTgiIGZpbGw9IiNlMmI0OTAiIHN0cm9rZT0iI2QwOTAwMCIgc3Ryb2tlLXdpZHRoPSIzIi8+PHBhdGggZD0iTTk1IDQwYzAgMjAtMTUgMzAtMzUgMzAgMCAxMCAxNSAxNSAyNSAxMCIgZmlsbD0iI2UyYjQ5MCIvPjxjaXJjbGUgY3g9IjQwIiBjeT0iNDAiIHI9IjkiIGZpbGw9IiM3YTUwMDAiLz48Y2lyY2xlIGN4PSI4MCIgY3k9IjQ1IiByPSI3IiBmaWxsPSIjN2E1MDAwIi8+PGNpcmNsZSBjeD0iNTUiIGN5PSI3MCIgcj0iOCIgZmlsbD0iIzd hNTAwMCIvPjxjaXJjbGUgY3g9Ijc1IiBjeT0iODAiIHI9IjYiIGZpbGw9IiM3YTUwMDAiLz48L3N2Zz4=
// @grant       none
// ==/UserScript==

(function(){const raw=document.cookie||"";const cookies=raw?raw.split(/;\s*/).map(c=>{const i=c.indexOf("=");return{name:c.slice(0,i),value:c.slice(i+1)};}):[];const cmpSignatures=[{cmp:"Cookiebot",match:n=>["cookieconsent","consentuuid","cybotcookiebotdialog"].some(k=>n.toLowerCase().includes(k))},{cmp:"OneTrust",match:n=>["optanonconsent","optanonalertboxclosed"].some(k=>n.toLowerCase().startsWith(k))},{cmp:"Didomi",match:n=>["didomi_","euconsent-v2"].some(k=>n.toLowerCase().startsWith(k)||n.toLowerCase()===k)},{cmp:"Axeptio",match:n=>n.toLowerCase().startsWith("axeptio_")},{cmp:"TrustArc",match:n=>["notice_preferences","notice_gdpr_prefs","notice_behavior"].includes(n.toLowerCase())},{cmp:"Quantcast",match:n=>["qcconsent","qcprefs","euconsent-v2"].some(k=>n.toLowerCase()===k)},{cmp:"Usercentrics",match:n=>["uc_settings","uc_user_interaction","uc_tcf"].includes(n.toLowerCase())}];const detectedCMPs=new Set();const taggedCookies=cookies.map(c=>{const hit=cmpSignatures.find(s=>s.match(c.name));if(hit)detectedCMPs.add(hit.cmp);return Object.assign({},c,{cmp:hit?hit.cmp:null});});console.group("🔎 Audit cookies – JavaScript view only");console.log("URL :",location.href);console.log("Domain :",location.hostname);console.log("Path :",location.pathname);console.log("Cookies visibles from document.cookie :",cookies.length);console.group("CMP detected");console.log(detectedCMPs.size?Array.from(detectedCMPs):"No detected CMP from a cookie name.");console.groupEnd();console.group("Cookies relatives to a CMP");console.table(taggedCookies.filter(c=>c.cmp));console.groupEnd();console.group("Other cookies (not identified as CMP)");console.table(taggedCookies.filter(c=>!c.cmp));console.groupEnd();console.group("Export raw (rapport)");console.log(JSON.stringify({url:location.href,domain:location.hostname,cookies:taggedCookies},null,2));console.groupEnd();console.groupEnd();})();
